export declare const
  podStart: number, podEnd: number, podEndDirective: number, podText: number,
  PodDirective: number, PodHeading: number, PodStrong: number, PodEmphasis: number,
  PodCode: number, PodLink: number, PodFormat: number,
  BlockComment: number, DocComment: number, LineComment: number, Pod: number, Heredoc: number,
  MethodName: number, Version: number, Regex: number, Operator: number, Number: number,
  radixNumber: number, PairKey: number,
  VariableName: number, AttributeName: number, SpecialVariable: number, operatorVariable: number,
  Identifier: number, TypeName: number, StringLiteral: number, Interpolation: number,
  self: number, True: number, False: number, Nil: number,
  PackageName: number, RoutineName: number, methodRoutineName: number, RegexName: number,
  EnumName: number, SubsetName: number, ConstantName: number,
  methodDot: number, declaredName: number, declaredMethodName: number, smiley: number,
  plainName: number, wordOperator: number,
  rawString: number, quoteStart: number, quoteContent: number, quoteNestOpen: number,
  quoteNestClose: number, quoteEnd: number, regexBody: number
