export declare const
  podStart: number, podEnd: number, podEndDirective: number, podText: number,
  PodDirective: number, PodHeading: number, PodStrong: number, PodEmphasis: number,
  PodCode: number, PodLink: number, PodFormat: number,
  BlockComment: number, DocComment: number, LineComment: number, Pod: number, Heredoc: number,
  rawHeredoc: number, interpolatingHeredoc: number, heredocStart: number,
  MethodName: number, Version: number, Regex: number, Operator: number, Number: number,
  radixNumber: number, PairKey: number,
  VariableName: number, AttributeName: number, SpecialVariable: number, operatorVariable: number,
  Identifier: number, TypeName: number, StringLiteral: number, Interpolation: number,
  self: number, True: number, False: number, Nil: number, multi: number, proto: number, only: number,
  PackageName: number, RoutineName: number, methodRoutineName: number, RegexName: number,
  EnumName: number, SubsetName: number, ConstantName: number,
  methodDot: number, declaredName: number, declaredMethodName: number, smiley: number, noSmiley: number,
  plainName: number, multiName: number, multiRoutineName: number, wordOperator: number,
  rawString: number, quoteStart: number, quoteContent: number, quoteNestOpen: number,
  quoteNestClose: number, quoteEnd: number, regexBody: number, regexLiteral: number, transliteration: number,
  regexStart: number, regexBodyEnd: number, regexLitOpen: number, regexLitClose: number,
  regexText: number, CharacterClass: number, Assertion: number,
  regexQuote: number, regexOperator: number, regexComment: number, regexBlockComment: number,
  regexCapture: number
